var express = require("express")
var app = express()
app.set("view engine","ejs")
var router = require("./router/router")
app.get("/",router.showIndex)
app.get("/addBook",router.addBook)
app.get("/addBookView",router.addBookView)
app.get("/editBook",router.editBook)
app.listen(3000)